#!/usr/bin/env bash

if
  [[ -s "/home/lucas/ruby/frogger/.gs/environment" ]]
then
  source "/home/lucas/ruby/frogger/.gs/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/lucas/ruby/frogger/.gs/environment'" >&2
  exit 1
fi
